DROP TABLE IF EXISTS `Reservation`;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS `Menu`;
DROP TABLE IF EXISTS `Restaurant`;

CREATE TABLE `User`
(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Mdp BINARY(64) NOT NULL,
	Nom VARCHAR(30) NOT NULL,
	Prenom VARCHAR(30) NOT NULL,
	Type VARCHAR(16) NOT NULL CHECK (Type in ("CLIENT","ADMIN"))
);

CREATE TABLE `Menu`
(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nom VARCHAR(30) NOT NULL,
	Description VARCHAR(150) NOT NULL,
	Prix FLOAT NOT NULL,
	Img VARCHAR(50) NOT NULL,
	Allergene VARCHAR(200) NOT NULL,
	Type VARCHAR(15) NOT NULL
);

CREATE TABLE `Restaurant`
(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	Nom VARCHAR(30) NOT NULL,
	Num_rue INTEGER NOT NULL,
	Rue VARCHAR(100) NOT NULL,
	Cp INTEGER NOT NULL,
	Ville VARCHAR(50) NOT NULL,
	Couv_Max INTEGER NOT NULL,
	Horaire_ouverture INTEGER NOT NULL,
	Horaire_Fermeture INTEGER NOT NULL
);

CREATE TABLE `Reservation`
(
	Id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
	User INTEGER NOT NULL,
	Restaurant INTEGER NOT NULL,
	Nombre_Couvert INTEGER NOT NULL,
	La_Date Date NOT NULL,
    FOREIGN KEY (User) REFERENCES User (Id),
    FOREIGN KEY (Restaurant) REFERENCES Restaurant (Id)
);